<a href="https://colab.research.google.com/github/Ellyzahardianty/Latihan_Pertemuan_3_DAA/blob/main/DAA_PERTEMUAN_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Struktur data dalam Python: Lists

Latihan 1

In [ ]:
from datetime import date

# Informasi mahasiswa
Mahasiswa = {
    "Nama": "Ellyza", "NIM": "2022071015", "Prodi": "Informatika",
    "Mata Kuliah": "DAA", "Tanggal Hari Ini": date.today().strftime("%d/%m/%Y"),"Nama Universitas": "Universitas Pembangunan Jaya"
}

# Menampilkan informasi mahasiswa
print("Informasi Mahasiswa:", Mahasiswa)

Informasi Mahasiswa: {'Nama': 'Ellyza', 'NIM': '2022071015', 'Prodi': 'Informatika', 'Mata Kuliah': 'DAA', 'Tanggal Hari Ini': '15/09/2023', 'Nama Universitas': 'Universitas Pembangunan Jaya'}


Latihan 2

In [ ]:
print(Mahasiswa["NIM"])

2022071015


In [ ]:
print(Mahasiswa["Nama"])

Ellyza


Latihan 3

In [ ]:
print(Mahasiswa["Nama Universitas"])

Universitas Pembangunan Jaya


In [ ]:
print(Mahasiswa["NIM"], Mahasiswa["Prodi"])

2022071015 Informatika


  Latihan 4

In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
  print (aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


Latihan 5

In [ ]:
Mahasiswa = ["Ellyza Hardianty", "2022071010", "Informatika",
             "DAA", "Universitas Pembangunan Jaya", "Today"]
for mhs in Mahasiswa:
  print( "UPJ " + mhs)

UPJ Ellyza Hardianty
UPJ 2022071010
UPJ Informatika
UPJ DAA
UPJ Universitas Pembangunan Jaya
UPJ Today


Latihan 6

In [ ]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
for kampus in UPJ:
 print (kampus)

Universitas
Pembangunan
Jaya


Latihan 7

In [ ]:
nested_tuple = (100, 200, 400, 600, 300, 400, 800)
Hasil = (pertama, kedua, ketiga, keempat)
print(Hasil)

(100, (200, 400, 600), 300, (400, 800))


Latihan 8

In [ ]:
data_mahasiswa = {
    "Nama": "Ellyza",
    "NIM": 2022071010,
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
print(data_mahasiswa)

{'Nama': 'Ellyza', 'NIM': 2022071010, 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


Latihan 9

In [ ]:
yellow = {'rose', 'blood', 'fire hydrant', 'leaves'}
red = {'dandelions', 'leaves', 'fire hydrant'}

print(yellow|red)
print(yellow&red)

{'leaves', 'blood', 'fire hydrant', 'dandelions', 'rose'}
{'fire hydrant', 'leaves'}


Latihan 10

In [7]:
import pandas as pd
df = pd.DataFrame([
    ['1','Informatika',50,30,20],
    ['2','Sistem informasi',55,30,25],
    ['3','Teknik Sipil',40,30,10]
])
df.columns = ['No','Prodi','Mahasiswa','Laki-laki','Perempuan']
data = {'No': ['1','2','3'],
        'Prodi' : ['Informatika','Sistem Inormasi','Teknik Sipil'],
        'Mahasiswa': [50,55,40],
        'Laki-Laki' : [30,30,30],
        'Perempuan' : [20,25,10],
        }

df = pd.DataFrame(data, index=['a','b','c'])

df.head()

No            Prodi  Mahasiswa  Laki-Laki  Perempuan
a  1      Informatika         50         30         20
b  2  Sistem Inormasi         55         30         25
c  3     Teknik Sipil         40         30         10

Latihan 11

In [12]:
import numpy as np  # Import numpy

matriks = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print("Matriks:")
print(matriks)

# Transpose the numpy array
transpose = np.transpose(matriks)
print("T-Matriks:")
print(transpose)

Matriks:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
T-Matriks:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


Latihan 12

In [14]:
# Tree
print("# Tree\n")

# Membuat class tree
class Node:
    def __init__(self,data):
        self.left = None
        self.right = None
        self.data = data
    def print_tree(self):
        if self.left:
            self.left.print_tree()
        print( self.data),
        if self.right:
            self.right.print_tree()

# Penggunaan class tree
root = Node(2)#root
root.left = Node(3) #child kiri dari root
root.right = Node(5) #child kanan dari root
root.left.left = Node(7) #child kiri dari 3
root.left.right = Node(9) #child kanan dari 3
root.right.left = Node(11) #child kiri dari 5
root.right.right = Node(13) #child kanan dari 5
root.print_tree()


# Tree

7
3
9
2
11
5
13
